"""Auto-generated by paste_urls.py – review and copy entries into url_list.py."""

OSHA_URLS = [
    # ── Part 1926 ────────────────────────────────────────────────────────────
    ("1926.95 - Criteria for personal protective equipment.",
     "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.95"),
    ("1926.96 - Occupational foot protection.",
     "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.96"),
    ("1926.97 - Electrical protective equipment.",
     "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.97"),
    ("1926.98 - [Reserved]",
     "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.98"),
    ("1926.100 - Head protection.",
     "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.100"),
    ("1926.101 - Hearing protection.",
     "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.101"),
    ("1926.102 - Eye and face protection.",
     "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.102"),
    ("1926.103 - Respiratory protection.",
     "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.103"),
    ("1926.104 - Safety belts, lifelines, and lanyards.",
     "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.104"),
    ("1926.105 - Safety nets.",
     "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.105"),
    ("1926.106 - Working over or near water.",
     "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.106"),
    ("1926.107 - Definitions applicable to this subpart.",
     "https://www.osha.gov/laws-regs/regulations/standardnumber/1926/1926.107"),
]
